name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  DOCKER_USERNAME: ajayshakya786
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKERHUB_REPO: alumna-db-service
  PROJECT_PATH: /home/ubuntu/alumna-backend-db-service

jobs:
  build-and-push:
    name: Build & Push Multi-Arch Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build and Push Multi-Arch Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_USERNAME }}/${{ env.DOCKERHUB_REPO }}:latest
          platforms: linux/amd64,linux/arm64

  deploy-on-ec2:
    name: Deploy on AWS EC2
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Connect to EC2 and restart Docker Compose
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ${{ env.PROJECT_PATH }} && restart-docker-compose
